# Generated by Django 4.2 on 2023-04-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='library_branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('publisher_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='book_authors',
            fields=[
                ('author_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.publisher'),
        ),
        migrations.CreateModel(
            name='book_loans',
            fields=[
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.book')),
                ('date_out', models.DateField()),
                ('due_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.library_branch')),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='book_copies',
            fields=[
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.book')),
                ('no_copies', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.library_branch')),
            ],
        ),
    ]
